### PR TITLE
fix(use-swrv): revalidate with revalidateOnFocus: false even document is hidden

### PR DESCRIPTION
**Pull request by suhaotian**
fix a weird bug in development.

### CODE REVIEW

**Comment by adamdehaven** [comment]
@suhaotian can you please provide a description and possibly a reproduction so we can take a look at the problem this PR is attempting to solve?

**Comment by suhaotian** [comment]
@adamdehaven sure, but later. thanks

**Comment by suhaotian** [comment]
@adamdehaven 

The live repoduce page here: https://vitejsvitexgq4p5-1wy2--5173--d830b1a2.local-credentialless.webcontainer.io/

How to reproduce: 

- open the page, then switch to others tab
- after a few seconds switch back the page, we will found the two count value not the same, but should same.

with `revalidateOnFocus: true` is ok, but in my case, i need `revalidateOnFocus: false`

The reproduce code here: https://stackblitz.com/edit/vitejs-vite-xgq4p5?file=package.json,src%2FSWRV-Counter%2FCounter.vue,src%2FApp.vue,src%2FSWRV-Counter%2FuseCount.ts&terminal=dev

**Comment by adamdehaven** [comment]
I'm still not sure I understand your change. 

If `revalidateOnFocus` is set to `false` if the page is not focused, why would we not want to set `isValidating` to `false`?

**Comment by suhaotian** [comment]
if we already set `revalidateOnFocus` to `false`, and we in other tabs, `websocket` notify us to update some data in the page, but never has no chance, because `(!config.isDocumentVisible() && !isFirstFetch)` this line  always return early.

**Pull request closed without merging**
