### PR TITLE
feat(ssr) add ssr support

### PR DESCRIPTION
**Pull request by darrenjennings**
* supports vue native ssr and specific nuxt context

Credit goes to @Atinux for this one as he provided the code and helped iterate with me. Thank you!

Sadly, the test did not work as expected, since window is currently always defined when calling renderToString... 🤔

### CODE REVIEW

**Comment by Atinux** [comment]
This is why I was using `vm.$isServer` :)

**Comment by darrenjennings** [comment]
@Atinux maybe you can get it to work but `$isServer` seems to be true as well. I will put it back actually the way you had it but wasn't able to get it working

**Comment by Atinux** [comment]
Oh I see, you need to go with the bundleRenderer to make it work: https://ssr.vuejs.org/guide/bundle-renderer.html#enter-bundlerenderer

**Comment by darrenjennings** [comment]
@Atinux afaict bundlerenderer would need a transpiled webpack bundle in order to work. do you have an example of this working? Was looking at https://github.com/vuejs/vue/blob/dev/test/ssr/ssr-bundle-render.spec.js#L42

**Comment by Atinux** [comment]
We have some test for vue-meta that could help: https://github.com/nuxt/vue-meta/tree/master/test

You need to create a `fixture` with a basic Vue app (using swrv) that you will build with Webpack to then test it 😬

**Comment by darrenjennings** [comment]
Fixes #10

**Pull request merged**
