### PR TITLE
refactor(document-visible): modify isDocumentVisible timing

### PR DESCRIPTION
**Pull request by NeoLSN**
Consider this scenario.
1. A user triggered a long time task to get a data, which might be longer than 15 seconds, in page A. `useSWRV('dynamicKey', fetcher)`
2. Re-route to page B after the task done. The page B need to be constructed with data from that task. 

Issue:
If the user switch to another Chrome tab when the task was running, then the page B won't be setup properly.
Because the page B won't get data when calling `useSWRV('dynamicKey')`.

Expected:
Should get data last known state when UI setup in document invisible mode.

BTW, in SWR, you can get last known state, but won't trigger the fetcher.
https://github.com/vercel/swr/blob/e76d30973bf623149ac4a61c81b0d3e4c8d79d93/src/use-swr.ts#L238-L253

### CODE REVIEW

**Comment by darrenjennings** [comment]
@NeoLSN what is the bug exactly?

**Comment by NeoLSN** [comment]
> @NeoLSN what is the bug exactly?

Oh, I forgot to update description.

**Comment by NeoLSN** [comment]
@darrenjennings Can you release this patch to NPM? or is there any concern? I need to this to solve my current project issue.

**Comment by darrenjennings** [comment]
@NeoLSN sorry about that, yes it is published now under `0.7.3`

**Comment by NeoLSN** [comment]
@darrenjennings Thank you.

**Pull request merged**
